# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20151204_1329'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='registration',
            new_name='raw_matricule',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1)),
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='raw_matricule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set([]),
        ),
    ]
